#!/usr/bin/env python3
"""Build immutable source pairs; attest exact measured bytes, never update public docs."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tarfile
import io

ENGINE = '4.7.2.stable.official.ed1daf0bf'
ASSETS = ['index.html', 'index.js', 'index.wasm', 'index.pck', 'campaign-viewport.js', 'dispatch-storage.js']
ROOT = Path(__file__).resolve().parents[3]


def digest(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def source_map(root):
    return {str(p.relative_to(root)): digest(p) for p in sorted((root / 'flotra-campaign').rglob('*'))
            if p.is_file() and '.godot' not in p.relative_to(root).parts}


def run(args, log, env=None):
    with log.open('w') as output:
        subprocess.run(args, cwd=ROOT, env=env, stdout=output, stderr=subprocess.STDOUT, check=True)


def prepare(args):
    out = Path(args.output).resolve()
    out.mkdir(parents=True, exist_ok=False)  # Never overwrite a previous measured series.
    frozen_path = ROOT / 'FLOTRA_NAVIGATION_ARTIFACTS_2026-10-08.json'
    frozen = json.loads(frozen_path.read_text())
    assert args.control == frozen['controlCommit'], 'Keep the established public control ref'
    for ref in (args.control, args.candidate):
        assert re.fullmatch('[0-9a-f]{40}', ref), 'Immutable full commit required'
        assert subprocess.check_output(['git', 'rev-parse', ref + '^{commit}'], cwd=ROOT, text=True).strip() == ref
    godot = str(Path(args.godot).resolve())
    assert subprocess.check_output([godot, '--version'], text=True).strip() == ENGINE
    manifest = {'kind': 'flotra-source-export-pair-v1', 'godot': ENGINE,
                'scope': 'Prospective temporary source exports; not public-artifact qualification',
                'controlCommit': args.control, 'candidateCommit': args.candidate,
                'frozenPublicManifestSHA256': digest(frozen_path),
                'controlRebuildPolicy': 'Compare regenerated A to immutable public A; existing scene-ID whitelist only',
                'candidatePolicy': 'Prospective exact generated bytes; no equality claim against old published B',
                'harnessSHA256': {name: digest(ROOT / name) for name in [
                    'flotra-campaign/tests/release/prepare_source_comparison.py',
                    'flotra-campaign/tests/release/browser_combined_performance.cjs',
                    'flotra-campaign/tests/release/source_export_contract.cjs',
                    'flotra-campaign/tests/release/browser_export_contract.cjs',
                    'flotra-campaign/tests/release/browser_growth_journey.cjs',
                    'flotra-campaign/tests/release/verify_writer_export.py',
                    'flotra-campaign/tests/release/diagnose_writer_pack.py',
                    'scripts/flotra_inspect_scene_ids.gd']}, 'variants': {}}
    for label, ref in [('A', args.control), ('B', args.candidate)]:
        base = out / label
        source = base / 'source'
        source.mkdir(parents=True)
        archive = subprocess.check_output(['git', 'archive', ref, 'flotra-campaign', 'docs/godot-jobs-preview'], cwd=ROOT)
        with tarfile.open(fileobj=io.BytesIO(archive)) as tar:
            tar.extractall(source, filter='data')
        before = source_map(source)
        (base / 'source-before.json').write_text(json.dumps(before, indent=2))
        env = dict(os.environ)
        # Disposable native profile; templates are a read-only input, not fetched here.
        for name, directory in [('XDG_DATA_HOME', 'data'), ('XDG_CONFIG_HOME', 'config'), ('XDG_CACHE_HOME', 'cache')]:
            location = base / 'profile' / directory
            location.mkdir(parents=True)
            env[name] = str(location)
        template_target = Path(env['XDG_DATA_HOME']) / 'godot/export_templates'
        template_target.parent.mkdir(parents=True)
        template_target.symlink_to(Path(args.templates).resolve(), target_is_directory=True)
        env['GODOT'] = godot
        run([godot, '--headless', '--editor', '--path', str(source / 'flotra-campaign'), '--import'], base / 'import.log', env)
        export = base / 'web'
        run(['bash', str(source / 'flotra-campaign/export_web.sh'), str(export)], base / 'export.log', env)
        assert source_map(source) == before, 'Import/export changed immutable project sources'
        html = (export / 'index.html').read_text()
        config = json.loads(re.search(r'const GODOT_CONFIG = (\{.*?\});', html)[1])
        assert config['persistentPaths'] == [] and config['fileSizes']['index.pck'] == (export / 'index.pck').stat().st_size
        for name in ['index.js', 'index.wasm']:
            assert digest(export / name) == frozen['controlAssetsSHA256'][name], 'Official pinned engine bytes'
        for name in ['campaign-viewport.js', 'dispatch-storage.js']:
            assert (export / name).read_bytes() == (source / 'flotra-campaign' / name).read_bytes()
        if label == 'A':
            public = source / 'docs/godot-jobs-preview'
            assert {name: digest(public / name) for name in ASSETS} == frozen['controlAssetsSHA256']
            # Same existing verifier and exact whitelist; no broader ID normalization.
            verification = base / 'public-control-verification'
            verification.mkdir()
            prospective_control = {'godot': ENGINE, 'candidateAssetsSHA256': frozen['controlAssetsSHA256'],
                                   'controlAssetsSHA256': frozen['controlAssetsSHA256'], 'sourceSHA256': before}
            manifest_path = verification / 'immutable-control.json'
            manifest_path.write_text(json.dumps(prospective_control, indent=2))
            inspector = ROOT / 'scripts/flotra_inspect_scene_ids.gd'
            for prefix, pack in [('candidate', public / 'index.pck'), ('exported', export / 'index.pck')]:
                inspect_env = {**env, 'SCENE_ID_REPORT': str(verification / (prefix + '-scenes.json'))}
                run([godot, '--headless', '--main-pack', str(pack), '--script', str(inspector)], verification / (prefix + '-inspect.log'), inspect_env)
            run([sys.executable, str(ROOT / 'flotra-campaign/tests/release/verify_writer_export.py'), str(export), str(verification), str(source)],
                verification / 'verification.log', {**env, 'FLOTRA_EXPORT_PROVENANCE': str(manifest_path)})
        manifest['variants'][label] = {'commit': ref, 'sourceDirectory': str(source), 'exportDirectory': str(export),
                                       'sourceSHA256': before, 'assetsSHA256': {name: digest(export / name) for name in ASSETS},
                                       'allExportAssetsSHA256': {p.name: digest(p) for p in sorted(export.iterdir()) if p.is_file()}}
        (base / 'source-after.json').write_text(json.dumps(source_map(source), indent=2))
    manifest['controlQualification'] = json.loads((out / 'A/public-control-verification/full-export-comparison.json').read_text())
    assert manifest['controlQualification']['status'] == 'pass'
    assert all(digest(ROOT / name) == value for name, value in manifest['harnessSHA256'].items())
    # Only written after both exports and the independent pinned-control comparison succeed.
    (out / 'prospective-manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    for option in ['control', 'candidate', 'output', 'godot', 'templates']:
        parser.add_argument('--' + option, required=True)
    prepare(parser.parse_args())
