#!/usr/bin/env node
'use strict';
// Real mouse/touch proof of the revised pause header using disposable synthetic
// in-flight saves. Does not mutate game data through a test API.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {chromium}=require('playwright');
const url=new URL(process.argv[2]);assert.ok(['127.0.0.1','localhost'].includes(url.hostname),'Loopback only');url.searchParams.set('phone_qa','1');
const out=path.resolve(process.argv[3]);fs.mkdirSync(out,{recursive:true});
const fixture=JSON.parse(fs.readFileSync(path.join(process.argv[4],'late.json'),'utf8'));
const report={scope:'Actual synthetic saved-job pause/resume header pixels; no user data',fixtureEncodedSHA256:crypto.createHash('sha256').update(fixture.encoded).digest('hex'),cases:[]};
const ui=p=>p.evaluate(()=>window.FlotraViewport?.uiMetrics);
async function tap(p,name,mobile){await p.waitForFunction(name=>window.FlotraViewport?.uiMetrics?.buttons.some(b=>b.name===name&&b.visible&&!b.disabled),name);const b=(await ui(p)).buttons.find(b=>b.name===name&&b.visible);const r=await p.locator('#canvas').boundingBox();const x=r.x+b.x+b.width/2,y=r.y+b.y+b.height/2;mobile?await p.touchscreen.tap(x,y):await p.mouse.click(x,y);await p.waitForTimeout(250);}
function header(s,w,h,running){const jobs=s.buttons.filter(b=>b.visible&&b.name==='WorkChoice');assert.equal(jobs.length,1);assert.equal(jobs[0].text,'仕事');const b=s.buttons.find(b=>b.name==='PauseResume');assert.ok(b.visible&&!b.disabled);assert.equal(b.text,running?(w>=1000?'一時停止':'停止'):'再開');assert.ok(b.fontSize>=18&&b.x>=0&&b.y>=0&&b.x+b.width<=w&&b.y+b.height<=(w>=1000?60:76));if(w>=1000)assert.ok(b.width>=108);const labels=s.labels.filter(l=>l.x===(w>=1000?220:104)&&l.y===(w>=1000?14:40));assert.equal(labels.length,1);assert.ok(labels[0].fontSize>=18&&labels[0].width>0);for(const other of s.buttons.filter(v=>v.visible&&v.name!==b.name&&v.y<60)){assert.ok(b.x>=other.x+other.width||other.x>=b.x+b.width||b.y>=other.y+other.height||other.y>=b.y+b.height,'Header buttons do not overlap');}return{pause:b,statusLabel:labels[0],world:s.worldRect};}
async function shot(p,item,name){await p.screenshot({path:path.join(out,item.name+'-'+name+'.jpg'),type:'jpeg',quality:85,scale:'css'});item.states[name]=await ui(p);console.log('NAVIGATION_HEADER_SCREEN '+JSON.stringify({case:item.name,state:name,header:item.measurements[name]}));}
(async()=>{let browser;try{browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true});for(const [w,h,dpr] of [[1280,720,1],[375,667,2]]){const mobile=w<1000,item={name:`${w}x${h}-dpr${dpr}`,states:{},measurements:{},errors:[]};report.cases.push(item);const context=await browser.newContext({viewport:{width:w,height:h},deviceScaleFactor:dpr,isMobile:mobile,hasTouch:mobile,serviceWorkers:'block'});const p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>item.errors.push(e.message));p.on('console',m=>{if(m.type()==='error')item.errors.push(m.text());});try{await context.addInitScript(encoded=>localStorage.setItem('flotra.campaign.release.v1',encoded),fixture.encoded);await p.goto(url.href,{waitUntil:'domcontentloaded',timeout:60000});await p.waitForFunction(()=>window.FlotraViewport?.uiMetrics?.sheet==='entry',null,{timeout:120000});await tap(p,'CloseSheet',mobile);await p.waitForFunction(()=>window.FlotraViewport?.uiMetrics?.sheet==='');let s=await ui(p);assert.equal(s.trialRunning,false);item.measurements.restoredPaused=header(s,w,h,false);await shot(p,item,'restoredPaused');const before=s.simTime;await tap(p,'PauseResume',mobile);await p.waitForFunction(before=>window.FlotraViewport.uiMetrics.trialRunning&&window.FlotraViewport.uiMetrics.simTime>before,before);s=await ui(p);item.measurements.running=header(s,w,h,true);await shot(p,item,'running');await tap(p,'PauseResume',mobile);await p.waitForFunction(()=>!window.FlotraViewport.uiMetrics.trialRunning);s=await ui(p);item.measurements.paused=header(s,w,h,false);await shot(p,item,'paused');const time=s.simTime;await p.waitForTimeout(700);assert.equal((await ui(p)).simTime,time,'Explicit pause stops foreground progression');assert.deepEqual(item.errors,[]);item.status='passed';}catch(e){item.status='failed';item.error=e.stack;console.error('NAVIGATION_HEADER_FIRST_FAILURE '+JSON.stringify({case:item.name,error:e.stack}));await shot(p,item,'failure').catch(()=>{});throw e;}finally{await context.close();fs.writeFileSync(path.join(out,'navigation-headers.json'),JSON.stringify(report,null,2));}}}catch(e){report.error=e.stack;process.exitCode=1;}finally{if(browser)await browser.close();fs.writeFileSync(path.join(out,'navigation-headers.json'),JSON.stringify(report,null,2));}})();
